### ISSUE TITLE
Create a readme file and a basic program for mathematical operations

### ISSUE THREAD

**Issue by ghost** [shvedoff98/cplusplus_basics#1]
Hello , I was wondering if I could create a readme file for the repo as well as create a simple mathematical program explaining the basic operations of C++

Could you let me know where I should store the file in the branch ?

**Comment by shvedoff98** [comment]
Hello, you can definitely create whatever you want, so choose where to store it on your own. I appreciate your interest in my repo :)

**Comment by ghost** [comment]
Thank you so much , will do 

No worries , thank you for having me :)
